name: Android CI
on:
  push:
    branches: [master,develop]
    tags: [v.*]
  pull_request:
    branches: [master,develop]
    tags: [v.*]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        distribution: 'adopt'
        java-version: 11
    - name: Build with Gradle
      run: ./gradlew assemble
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Publish package
        run: gradle publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}